spring.datasource.url=jdbc:postgresql://localhost:5432/hogwartsSchool
spring.datasource.username=neo
spring.datasource.password=dyalpsoge
spring.liquibase.change-log=classpath:liquibase/lesson-three.yml

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true